name: Compilar Calculadora PCR

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python Estable (3.12)
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Instalar librerías en la nube
      run: |
        pip install streamlit pandas pyinstaller

    - name: Buscar y Compilar EXE Automáticamente
      shell: powershell
      run: |
        $archivo = Get-ChildItem -Filter "lanzador.py" -Recurse | Select-Object -First 1
        if ($archivo) {
            Write-Host "¡Encontrado! Tus archivos están en: $($archivo.DirectoryName)"
            cd $archivo.DirectoryName
            pyinstaller --onefile --copy-metadata streamlit --add-data "app_web.py;." --add-data "calculos.py;." lanzador.py
        } else {
            Write-Error "Error: No se encontró 'lanzador.py' en ningún rincón del repositorio. Revisá si lo subiste."
            exit 1
        }

    - name: Guardar el resultado
      uses: actions/upload-artifact@v4
      with:
        name: Calculadora_PCR_Windows
        path: "**/dist/lanzador.exe"
